### ISSUE TITLE
Do not over-catch exceptions.

### ISSUE THREAD

**Issue by kdeldycke** [UMIACS/rgwadmin#10]
Is there a reason to catch all exceptions on each request as in https://github.com/UMIACS/rgwadmin/blob/1.1.2/rgwadmin/rgw.py#L132-L134 ?

The way all responses are normalized to `None` whatever happens doesn't help. There's no way to make the difference between an empty returned value of a regular request, and one that return nothing because it's failing, due to missing capabilities, network error or any internal issue.

What I suggest is to simply let the request raise an exception on error, and let the caller decide of an appropriate action. Exceptions are cheap in Python. Let's use and abuse them ! :smiley_cat:

What's your opinion @dyarnell ?

**Comment by kdeldycke** [comment]
Here is my exact use-case, in which I try to connect to a closed port (`6666`):

```python
Python 2.7.11 (default, Dec  5 2015, 14:44:53) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Persistent session history, tab completion and pretty printing are enabled.
>>> import rgwadmin
>>> rgwadmin.__version__
'1.1.2'
>>> conn = rgwadmin.RGWAdmin(server="192.168.10.1:6666", access_key="4OCF631N4FPJA90NEQ6U", secret_key="SrnIqlgNH5NJo1vu4U1BXXICUQBFq9cGBMVm5kSO")
>>> response = conn.get_users()
>>> repr(response)
'None'
>>> 
```

Here I expect the `conn.get_users()` call to raise an error instead of returning `None`.

**Comment by dyarnell** [comment]
I was thinking of just raising a ConnectionFailed exception at[0].  The logger will have all the underlying gory details of the requests failure.

```
class ConnectionFailed(RGWAdminException):
    """Requests connection failed."""
```

[0] - https://github.com/UMIACS/rgwadmin/blob/master/rgwadmin/rgw.py#L134

```
>>> logging.basicConfig(level=logging.DEBUG)
>>> import rgwadmin
>>> conn = rgwadmin.RGWAdmin(server="192.168.10.1:6666", access_key="4OCF631N4FPJA90NEQ6U", secret_key="SrnIqlgNH5NJo1vu4U1BXXICUQBFq9cGBMVm5kSO")
>>> response = conn.get_users()
DEBUG:rgwadmin.rgw:URL: https://192.168.10.1:6666/admin/metadata/user?format=json
DEBUG:rgwadmin.rgw:Access Key: 4OCF631N4FPJA90NEQ6U
DEBUG:rgwadmin.rgw:Verify: True  CA Bundle: None
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): 192.168.10.1
ERROR:rgwadmin.rgw:HTTPSConnectionPool(host='192.168.10.1', port=6666): Max retries exceeded with url: /admin/metadata/user?format=json (Caused by <class 'socket.error'>: [Errno 61] Connection refused)
Traceback (most recent call last):
  File "rgwadmin/rgw.py", line 131, in request
    r = m(url, headers=headers, auth=auth, verify=verify, data=data)
  File "/Users/derek/env/lib/python2.7/site-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/Users/derek/env/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/derek/env/lib/python2.7/site-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/derek/env/lib/python2.7/site-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/Users/derek/env/lib/python2.7/site-packages/requests/adapters.py", line 375, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='192.168.10.1', port=6666): Max retries exceeded with url: /admin/metadata/user?format=json (Caused by <class 'socket.error'>: [Errno 61] Connection refused)
```

**Comment by kdeldycke** [comment]
Re-raising `ConnectionFailed` sounds good to me.

**Comment by dyarnell** [comment]
Sorry let me just propose re-propagating the requests exception instead.   

```
diff --git a/rgwadmin/rgw.py b/rgwadmin/rgw.py
index e279c83..cb77769 100644
--- a/rgwadmin/rgw.py
+++ b/rgwadmin/rgw.py
@@ -131,7 +131,7 @@ class RGWAdmin:
             r = m(url, headers=headers, auth=auth, verify=verify, data=data)
         except Exception as e:
             log.exception(e)
-            return None
+            raise
         return self._load_request(r)

     def get_metadata(self, metadata_type, key=None):
```

```
>>> import rgwadmin
>>> conn = rgwadmin.RGWAdmin(server="192.168.10.1:6666", access_key="4OCF631N4FPJA90NEQ6U", secret_key="SrnIqlgNH5NJo1vu4U1BXXICUQBFq9cGBMVm5kSO")
>>> response = conn.get_users()
No handlers could be found for logger "rgwadmin.rgw"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "rgwadmin/rgw.py", line 164, in get_users
    return self.get_metadata(metadata_type='user')
  File "rgwadmin/rgw.py", line 144, in get_metadata
    return self.request('get', request_string)
  File "rgwadmin/rgw.py", line 131, in request
    r = m(url, headers=headers, auth=auth, verify=verify, data=data)
  File "/Users/derek/env/lib/python2.7/site-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/Users/derek/env/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/derek/env/lib/python2.7/site-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/derek/env/lib/python2.7/site-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/Users/derek/env/lib/python2.7/site-packages/requests/adapters.py", line 375, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='192.168.10.1', port=6666): Max retries exceeded with url: /admin/metadata/user?format=json (Caused by <class 'socket.error'>: [Errno 61] Connection refused)
```

**Comment by kdeldycke** [comment]
That will do ! :+1:

**Comment by dyarnell** [comment]
1.1.3 released with the re-raising of the request exception.

**Comment by kdeldycke** [comment]
Awesome ! :heart_eyes_cat:
