### ISSUE TITLE
Connection aborted, error(111, 'Connection refused'))

### ISSUE THREAD

**Issue by Tanyy** [UMIACS/rgwadmin#38]
hi  
I just cannot connectioned my Ceph cluster  and you can see my code like that:

```
from rgwadmin import RGWAdmin, RGWUser
import sys

def main():
    rgw  =  RGWAdmin(access_key = 'OW555ABE339I89QKC1NI' , secret_key = 'xB7Ttp66rgtqydONLJ4UsieTknE8KooXPrblV4eT' , server = 'http://10.211.55.61:8080' )
    rgw.create_user(
        uid = 'tmp' ,
        display_name = 'create by rgwadmin api' ,
        email = '' ,
        max_buckets = 10 )
    rgw.set_quota(
        uid = 'tmp' ,
        quota_type = 'user' ,
        max_size_kb = 1024 * 1024 ,
        enabled = True )
    #rgw.remove_user(uid = 'tmp' , purge_data = True )

if __name__ == '__main__':
    sys.exit(main())
```

my rgw user info :

```
{
    "user_id": "admin",
    "display_name": "admin",
    "email": "",
    "suspended": 0,
    "max_buckets": 1000,
    "auid": 0,
    "subusers": [],
    "keys": [
        {
            "user": "admin",
            "access_key": "OW555ABE339I89QKC1NI",
            "secret_key": "xB7Ttp66rgtqydONLJ4UsieTknE8KooXPrblV4eT"
        }
    ],
    "swift_keys": [],
    "caps": [
        {
            "type": "buckets",
            "perm": "*"
        },
        {
            "type": "usage",
            "perm": "*"
        },
        {
            "type": "users",
            "perm": "*"
        }
    ],
    "op_mask": "read, write, delete",
    "default_placement": "",
    "placement_tags": [],
    "bucket_quota": {
        "enabled": false,
        "check_on_raw": false,
        "max_size": -1,
        "max_size_kb": 0,
        "max_objects": -1
    },
    "user_quota": {
        "enabled": false,
        "check_on_raw": false,
        "max_size": -1,
        "max_size_kb": 0,
        "max_objects": -1
    },
    "temp_url_keys": [],
    "type": "rgw"
}
```

my ceph version : ceph version 12.2.11 (26dc3775efc7bb286a1d6d66faee0ba30ea23eee) luminous (stable)

python error code : 

```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    sys.exit(main())
  File "test.py", line 10, in main
    max_buckets = 10 )
  File "/usr/lib/python2.7/site-packages/rgwadmin/rgw.py", line 252, in create_user
    (self._admin, self._response, parameters))
  File "/usr/lib/python2.7/site-packages/rgwadmin/rgw.py", line 147, in request
    raise e
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
```

**Comment by Tanyy** [comment]
I was fixed it . this lib use https by default ,but i use http

**Comment by liammonahan** [comment]
Updated the [documentation](https://rgwadmin.readthedocs.io/en/latest/rgwadmin/getting-started.html) to help future users be aware of this default.
